In [327]:
import pandas as pd
import numpy as np

In [329]:
data=pd.read_csv('IMDB Dataset.csv')

In [330]:
data

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [331]:
data=data.sample(5000)

In [335]:
data

review sentiment
42692  With such actors as Ralph Richardson, Raymond ...  positive
6055   I enjoyed this movie a lot. I thought that the...  positive
11517  I have to admit that I approached this movie w...  positive
3517   This is a lovely tale of guilt-driven obsessio...  positive
114    The Assignment is an outstanding thriller with...  positive
...                                                  ...       ...
44465  I am so confused. What in the world was this m...  negative
13045  Tears of Kali is an original yet flawed horror...  positive
19587  I suggest that in the future, any movie made b...  negative
26592  It is hard to know what category to put this f...  positive
12793  I admit - I was lured to this one from the hyp...  negative

[5000 rows x 2 columns]

In [337]:
data['sentiment'].unique()

array(['positive', 'negative'], dtype=object)

In [339]:
data['sentiment']=data['sentiment'].replace({'negative':0,'positive':1})

C:\Users\JESMA\AppData\Local\Temp\ipykernel_17948\3361669265.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['sentiment']=data['sentiment'].replace({'negative':0,'positive':1})


In [341]:
data

review  sentiment
42692  With such actors as Ralph Richardson, Raymond ...          1
6055   I enjoyed this movie a lot. I thought that the...          1
11517  I have to admit that I approached this movie w...          1
3517   This is a lovely tale of guilt-driven obsessio...          1
114    The Assignment is an outstanding thriller with...          1
...                                                  ...        ...
44465  I am so confused. What in the world was this m...          0
13045  Tears of Kali is an original yet flawed horror...          1
19587  I suggest that in the future, any movie made b...          0
26592  It is hard to know what category to put this f...          1
12793  I admit - I was lured to this one from the hyp...          0

[5000 rows x 2 columns]

In [343]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 42692 to 12793
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     5000 non-null   object
 1   sentiment  5000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 117.2+ KB


In [345]:
data.isnull().sum()

review       0
sentiment    0
dtype: int64

In [347]:
import re

In [349]:
def clean_html(text):
    clear=re.compile('<.*?>')
    return re.sub(clear,'',text)

In [351]:
data['review']=data['review'].apply(clean_html)

In [353]:
data

review  sentiment
42692  With such actors as Ralph Richardson, Raymond ...          1
6055   I enjoyed this movie a lot. I thought that the...          1
11517  I have to admit that I approached this movie w...          1
3517   This is a lovely tale of guilt-driven obsessio...          1
114    The Assignment is an outstanding thriller with...          1
...                                                  ...        ...
44465  I am so confused. What in the world was this m...          0
13045  Tears of Kali is an original yet flawed horror...          1
19587  I suggest that in the future, any movie made b...          0
26592  It is hard to know what category to put this f...          1
12793  I admit - I was lured to this one from the hyp...          0

[5000 rows x 2 columns]

In [355]:
data['review'].iloc[6]

'"Love and Human Remains" is one of those obviously scripted, obviously acted, obviously staged flicks which is so obvious that the escape velocity from its contrivances and fabrication is beyond me. Not worth explaining, this amateurish flick tries to cram every clever line, every misanthropic overtone, every peculiar sexual predilection into one film with an absence of concern for making the pieces fit. In short, sensationalistic crap without the sensation...which pretty much just leaves crap.'

In [357]:
def remove_special(text):
    x=' '
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+' '
    return x        

In [359]:
data['review']=data['review'].apply(remove_special)

In [360]:
data['review']

42692     With such actors as Ralph Richardson  Raymond...
6055      I enjoyed this movie a lot  I thought that th...
11517     I have to admit that I approached this movie ...
3517      This is a lovely tale of guilt driven obsessi...
114       The Assignment is an outstanding thriller wit...
                               ...                        
44465     I am so confused  What in the world was this ...
13045     Tears of Kali is an original yet flawed horro...
19587     I suggest that in the future  any movie made ...
26592     It is hard to know what category to put this ...
12793     I admit   I was lured to this one from the hy...
Name: review, Length: 5000, dtype: object

In [361]:
def convert_lower(text):
    return text.lower()

In [362]:
data['review']=data['review'].apply(convert_lower)

In [363]:
data['review']

42692     with such actors as ralph richardson  raymond...
6055      i enjoyed this movie a lot  i thought that th...
11517     i have to admit that i approached this movie ...
3517      this is a lovely tale of guilt driven obsessi...
114       the assignment is an outstanding thriller wit...
                               ...                        
44465     i am so confused  what in the world was this ...
13045     tears of kali is an original yet flawed horro...
19587     i suggest that in the future  any movie made ...
26592     it is hard to know what category to put this ...
12793     i admit   i was lured to this one from the hy...
Name: review, Length: 5000, dtype: object

In [364]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\JESMA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [369]:
from nltk.corpus import stopwords

In [372]:
a=stopwords.words('english')

In [375]:
def remove_words(text):
    x=[]
    for i in text.split():
        if i not in a:
            x.append(i)
        else:
            pass
    return x        

In [377]:
data['review']=data['review'].apply(remove_words)

In [378]:
data

review  sentiment
42692  [actors, ralph, richardson, raymond, massey, c...          1
6055   [enjoyed, movie, lot, thought, plot, movie, re...          1
11517  [admit, approached, movie, sense, expectation,...          1
3517   [lovely, tale, guilt, driven, obsession, matis...          1
114    [assignment, outstanding, thriller, several, p...          1
...                                                  ...        ...
44465  [confused, world, movie, killer, motivation, s...          0
13045  [tears, kali, original, yet, flawed, horror, f...          1
19587  [suggest, future, movie, made, sci, fi, channe...          0
26592  [hard, know, category, put, film, films, set, ...          1
12793  [admit, lured, one, hype, stop, consider, sour...          0

[5000 rows x 2 columns]

In [379]:
from nltk.stem.porter import PorterStemmer

In [380]:
ps=PorterStemmer()

In [381]:
def stem_words(text):
    x=[]
    for i in text:
        x.append(ps.stem(i))
    return x    

In [382]:
data['review']=data['review'].apply(stem_words)

In [383]:
data['review'].iloc[5]

['despit',
 'quit',
 'far',
 'remov',
 'expect',
 'thoroughli',
 'impress',
 'dog',
 'bite',
 'dog',
 'rent',
 'know',
 'much',
 'essenti',
 'expect',
 'martial',
 'art',
 'action',
 'film',
 'standard',
 'hong',
 'kong',
 'action',
 'tradit',
 'devot',
 'fan',
 'end',
 'get',
 'someth',
 'entir',
 'differ',
 'bad',
 'thing',
 'film',
 'could',
 'classifi',
 'definit',
 'good',
 'action',
 'hand',
 'hand',
 'combat',
 'scene',
 'film',
 'definit',
 'primari',
 'focu',
 'charact',
 'infinit',
 'import',
 'film',
 'fight',
 'rather',
 'uncommon',
 'thing',
 'mani',
 'hong',
 'kong',
 'action',
 'movi',
 'realli',
 'quit',
 'surpris',
 'intricaci',
 'charact',
 'charact',
 'relationship',
 'film',
 'lead',
 'charact',
 'play',
 'edison',
 'chen',
 'realli',
 'good',
 'becom',
 'infinit',
 'complex',
 'end',
 'film',
 'ever',
 'thought',
 'would',
 'watch',
 'first',
 'thirti',
 'minut',
 'polic',
 'charact',
 'also',
 'defi',
 'expect',
 'thoroughli',
 'fact',
 'stark',
 'honest',
 'portr

In [391]:
def join(text):
    return ' '.join(text)

In [392]:
data['review']=data['review'].apply(join)

In [393]:
data.iloc[5]

review       despit quit far remov expect thoroughli impres...
sentiment                                                    1
Name: 17522, dtype: object

In [394]:
from sklearn.feature_extraction.text import CountVectorizer

In [395]:
X=data['review']
y=data['sentiment']

In [396]:
cv=CountVectorizer()

In [397]:
cv.fit_transform(data['review'])

<5000x26593 sparse matrix of type '<class 'numpy.int64'>'
	with 466908 stored elements in Compressed Sparse Row format>

In [409]:
X=cv.fit_transform(data['review']).toarray()

In [411]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [415]:
from sklearn.model_selection import train_test_split

In [417]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [419]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [421]:
y_train

46310    0
19457    1
37231    1
21943    0
14926    0
        ..
33176    0
11329    0
21443    0
21914    0
2466     0
Name: sentiment, Length: 3500, dtype: int64

In [423]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix

In [425]:
gnb=GaussianNB()

In [427]:
gnb.fit(X_train,y_train)

GaussianNB()

In [429]:
y_pred=gnb.predict(X_test)

In [431]:
gnb.score(X_test,y_test)

0.6246666666666667

In [433]:
ac=accuracy_score(y_test,y_pred)

In [435]:
ac

0.6246666666666667

In [437]:
cm=confusion_matrix(y_test,y_pred)

In [439]:
cm

array([[503, 235],
       [328, 434]], dtype=int64)